version: '3'

services:
  redis-server: 
    image: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - /srv/docker/redis:/var/lib/redis
  node-app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "3006:3006"
      - "3007:3007"
    command: npm start

